### ISSUE TITLE
Version 1.0.0 Release Checklist

### ISSUE THREAD

**Issue by DerZade** [gruppe-adler/grad_minui#22]
- [ ] #15 
- [ ] [ACE3 Compatibility Tips](https://github.com/gruppe-adler/grad_minui/wiki/ACE3-Compatibility-Tips)
- [ ] Adjust RELEASE GitHub Actions Workflow (uncomment [this line](https://github.com/gruppe-adler/grad_minui/blob/36550f49e70e470080c8b0bbd48b9f460944622a/.github/workflows/RELEASE.yml#L25))
- [ ] Add video & images to README
- [ ] Add video & images to Steam WS page
- [ ] Adjust YT-Video visibility
- [ ] Adjust visibility of Steam WS pages ([Main Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2574600875) and [ACE Compat Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2574699777))
- [ ] GitHub Release
- [ ] BI Forums post
